# Ансамбли

Поработаем с датасетом курсов на Udemy: https://www.kaggle.com/datasets/nayanack/udemy-courses

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML_training_data/udemy_courses.csv.xls')

In [ ]:
df

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3678 entries, 0 to 3677
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_id            3678 non-null   int64  
 1   course_title         3678 non-null   object 
 2   url                  3678 non-null   object 
 3   is_paid              3678 non-null   bool   
 4   price                3678 non-null   int64  
 5   num_subscribers      3678 non-null   int64  
 6   num_reviews          3678 non-null   int64  
 7   num_lectures         3678 non-null   int64  
 8   level                3678 non-null   object 
 9   content_duration     3678 non-null   float64
 10  published_timestamp  3678 non-null   object 
 11  subject              3678 non-null   object 
dtypes: bool(1), float64(1), int64(5), object(5)
memory usage: 319.8+ KB


In [ ]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

In [ ]:
set(list(df['level']))

{'All Levels', 'Beginner Level', 'Expert Level', 'Intermediate Level'}

In [ ]:
set(list(df['subject']))

{'Business Finance',
 'Graphic Design',
 'Musical Instruments',
 'Web Development'}

In [ ]:
X_to_onehot = df[['is_paid', 'level', 'subject']]

In [ ]:
enc = OneHotEncoder()

In [ ]:
X_cat_encoded = enc.fit_transform(X_to_onehot)

In [ ]:
scaler = MinMaxScaler()

In [ ]:
X_to_scale = df[['price', 'num_lectures', 'content_duration']]

In [ ]:
X_scaled = scaler.fit_transform(X_to_scale)

In [ ]:
X_scaled.shape

(3678, 3)

In [ ]:
X_cat_encoded.shape

(3678, 10)

In [ ]:
type(X_scaled)

numpy.ndarray

In [ ]:
type(X_cat_encoded)

scipy.sparse._csr.csr_matrix

In [ ]:
type( X_cat_encoded.todense())

numpy.matrix

In [ ]:
X = np.concatenate([X_scaled, X_cat_encoded.todense()], axis=1)

In [ ]:
X.shape

(3678, 13)

In [ ]:
X

matrix([[1.        , 0.06546855, 0.01910828, ..., 0.        , 0.        ,
         0.        ],
        [0.375     , 0.35173299, 0.49681529, ..., 0.        , 0.        ,
         0.        ],
        [0.225     , 0.06546855, 0.03184713, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.2       , 0.06161746, 0.04458599, ..., 0.        , 0.        ,
         1.        ],
        [0.25      , 0.04878049, 0.03821656, ..., 0.        , 0.        ,
         1.        ],
        [0.225     , 0.02567394, 0.02547771, ..., 0.        , 0.        ,
         1.        ]])

In [ ]:
X = np.asarray(X)

In [ ]:
X

array([[1.        , 0.06546855, 0.01910828, ..., 0.        , 0.        ,
        0.        ],
       [0.375     , 0.35173299, 0.49681529, ..., 0.        , 0.        ,
        0.        ],
       [0.225     , 0.06546855, 0.03184713, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.2       , 0.06161746, 0.04458599, ..., 0.        , 0.        ,
        1.        ],
       [0.25      , 0.04878049, 0.03821656, ..., 0.        , 0.        ,
        1.        ],
       [0.225     , 0.02567394, 0.02547771, ..., 0.        , 0.        ,
        1.        ]])

Ради интереса попробуем зависимую переменную тоже шкалировать:

In [ ]:
target_scaler = MinMaxScaler()

In [ ]:
scaled_y = target_scaler.fit_transform(np.array(df['num_subscribers'].tolist()).reshape(-1, 1))

In [ ]:
scaled_y

array([[0.0079837 ],
       [0.01038215],
       [0.0080841 ],
       ...,
       [0.00190761],
       [0.00111556],
       [0.0033504 ]])

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, scaled_y, test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [ ]:
def get_scores(y_true, y_pred):
  print('R2: ', r2_score(y_true, y_pred))
  print('MSE: ', mean_squared_error(y_true, y_pred))
  print('MAE: ', mean_absolute_error(y_true, y_pred))

## Bagging

In [ ]:
model = BaggingRegressor(estimator=LinearRegression(), n_jobs=-1, n_estimators=100)

In [ ]:
y_train.shape

(2942, 1)

In [ ]:
y_train.ravel().shape

(2942,)

In [ ]:
# .ravel() превращает двумерный массив в одномерный: это операция, обратная .reshape(-1, 1)
model.fit(X_train, y_train.ravel())

BaggingRegressor(estimator=LinearRegression(), n_estimators=100, n_jobs=-1)

In [ ]:
base_preds = model.predict(X_test)

In [ ]:
get_scores(y_test, base_preds)

R2:  0.14644957773611744
MSE:  0.001279872542635151
MAE:  0.013356940685893394


## Random Forest

In [ ]:
rf = RandomForestRegressor()

In [ ]:
rf.fit(X_train, y_train.ravel())

RandomForestRegressor()

In [ ]:
base_rf_preds = rf.predict(X_test)

In [ ]:
get_scores(y_test, base_rf_preds)

R2:  -0.20197944250916522
MSE:  0.0018023311161854043
MAE:  0.015169823696954387


## Grid Search в рандомном лесу

In [ ]:
forest_params = {'max_depth': [2, 5, 10, None], 'max_features': [0.3, 'sqrt', 1.0], 'n_estimators': [10, 100, 500]}

In [ ]:
gs = GridSearchCV(RandomForestRegressor(), forest_params, scoring='r2', verbose=1)

In [ ]:
gs.fit(np.asarray(X_train), y_train.ravel())

Fitting 5 folds for each of 36 candidates, totalling 180 fits


GridSearchCV(estimator=RandomForestRegressor(),
             param_grid={'max_depth': [2, 5, 10, None],
                         'max_features': [0.3, 'sqrt', 1.0],
                         'n_estimators': [10, 100, 500]},
             scoring='r2', verbose=1)

In [ ]:
gs.best_params_

{'max_depth': 5, 'max_features': 'sqrt', 'n_estimators': 100}

In [ ]:
gs_preds = gs.predict(X_test)

In [ ]:
get_scores(y_test, gs_preds)

R2:  0.04088117969808691
MSE:  0.0014381691007464914
MAE:  0.013244019866795489


## Gradient Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
# параметр verbose говорит, сколько информации о ходе обучения выводить в консоль
# параметр n_iter_no_change применяется для реализации early stopping: остановиться, когда ошибка не меняется n_iter_no_change шагов
gbr = GradientBoostingRegressor(n_estimators=100, random_state=0, verbose=10, n_iter_no_change=10)

In [ ]:
gbr.fit(X_train, y_train.ravel())

      Iter       Train Loss   Remaining Time 
         1           0.0011            0.85s
         2           0.0010            0.57s
         3           0.0010            0.46s
         4           0.0009            0.41s
         5           0.0009            0.37s
         6           0.0008            0.35s
         7           0.0008            0.33s
         8           0.0007            0.32s
         9           0.0007            0.31s
        10           0.0007            0.30s
        11           0.0007            0.29s
        12           0.0007            0.29s
        13           0.0006            0.29s
        14           0.0006            0.28s
        15           0.0006            0.27s


GradientBoostingRegressor(n_iter_no_change=10, random_state=0, verbose=10)

In [ ]:
gbr_preds = gbr.predict(X_test)

In [ ]:
get_scores(y_test, gbr_preds)

R2:  0.09597057217036353
MSE:  0.0013555642551783635
MAE:  0.013344216124048095


## Stacking

In [ ]:
from sklearn.linear_model import RidgeCV, LassoCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import StackingRegressor

In [ ]:
estimators = [('ridge', RidgeCV()),
              ('lasso', LassoCV(random_state=42)),
              ('knr', KNeighborsRegressor(n_neighbors=10))]

In [ ]:
final_estimator = GradientBoostingRegressor(n_estimators=25, random_state=42, verbose=10, n_iter_no_change=10)
reg = StackingRegressor(estimators=estimators, final_estimator=final_estimator)

In [ ]:
reg.fit(X_train, y_train.ravel())

      Iter       Train Loss   Remaining Time 
         1           0.0010            0.12s
         2           0.0009            0.11s
         3           0.0009            0.11s
         4           0.0008            0.10s
         5           0.0008            0.10s
         6           0.0007            0.10s
         7           0.0007            0.09s
         8           0.0007            0.09s
         9           0.0006            0.08s
        10           0.0006            0.08s
        11           0.0006            0.08s
        12           0.0006            0.07s
        13           0.0006            0.07s
        14           0.0006            0.06s
        15           0.0006            0.06s
        16           0.0005            0.05s
        17           0.0005            0.05s
        18           0.0005            0.04s
        19           0.0005            0.04s
        20           0.0005            0.03s


StackingRegressor(estimators=[('ridge', RidgeCV()),
                              ('lasso', LassoCV(random_state=42)),
                              ('knr', KNeighborsRegressor(n_neighbors=10))],
                  final_estimator=GradientBoostingRegressor(n_estimators=25,
                                                            n_iter_no_change=10,
                                                            random_state=42,
                                                            verbose=10))

In [ ]:
reg_preds = reg.predict(X_test)

In [ ]:
get_scores(y_test, reg_preds)

R2:  0.07542106446958519
MSE:  0.0013863776084201533
MAE:  0.012871158017514636
